services:
  yunyoo-monitor:
    build: .
    container_name: yunyoo-monitor
    restart: always
    env_file:
      - .env
    volumes:
      - ./stock_state.json:/app/stock_state.json
      - ./tasks.json:/app/tasks.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
