version: '3.8'

services:
  yunyoo-monitor:
    build: .
    container_name: yunyoo-monitor
    restart: always
    volumes:
      - ./stock_state.json:/app/stock_state.json
      - ./tasks.json:/app/tasks.json  # 新增挂载
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"